### PR TITLE
Reimplement some blocks

### LINKED ISSUE #19: date-format doesn't work with banana in the box
<input #fromInput datetime-picker
            [(ngModel)]="from"
            close-on-select="false"
            date-format="DD.MM.YYYY HH:mm"
    >

while from value (ISO string) is changed in component, date-format is not applied and input contain ISO 2016-09-13T16:50:46Z instead of 13.09.2016 16:50

I should note that initialization and changing value from datepicker works fine. Only external changes don't touch formatting.

Probably bug

### PR DESCRIPTION
**Pull request by visitek**
Fixes #19
DatetimePicker is interactive now. Model value is separated from emitted value.

### CODE REVIEW

**Comment by visitek** [comment]
<input datetime-picker
              [value]="value"
              (valueChange)="onValueChange($event)"
              close-on-select="false"
              date-format="DD.MM.YYYY HH:mm"
      >

**Comment by visitek** [comment]
I will change value nam back to ngModel for consistency. And fix readme.md. But BananaInTheBox is irrelevant anyway for this. Inpit has formatted value, but Date is emmited. Parent component should work with Date, not with formatted string. As it is now

**Comment by allenhwkim** [comment]
Is there a reason to change `ngModel` to `value`. It's confusing for me. e.g. "value"="value", [value]="value"

**Comment by visitek** [comment]
Yes, because ngModel is encapsulated and must be implemented both with ngModelChange. I this case the visible value of input is formatted, but real value is kept in Date. It can not be used with ngModel.

**Comment by visitek** [comment]
We can not emit formatted value as ngModelChange event, because it is not true. Event with Date is true output

**Comment by allenhwkim** [comment]
cool, one more request. could you change 8 space hard-tab to 2 space soft-tab? It makes my life a lot easier for consistency.

**Comment by visitek** [comment]
```html
<input datetime-picker
              [value]="fromTimeISO"
              (valueChange)="onFromChange($event)"
              close-on-select="false"
              date-format="DD.MM.YYYY HH:mm"
      >
```
better? :)

**Comment by visitek** [comment]
yes..

**Comment by allenhwkim** [comment]
The reason I am asking is that using "[value]" is **a breaking change**. With this release, all the existing user must change their code. Thus, it must be notified user as "BRAEKING CHANGES" for release. Can we make it [(ngModel)] deprecated if possible?

**Comment by visitek** [comment]
I'll try it

**Comment by visitek** [comment]
I've added non breaking changes. But it is really deprecated. ngModel can be used without reactive changes

**Comment by visitek** [comment]
create releases and handle breaking changes

**Comment by hamayunaziz** [comment]
is there any plnkr example??

**Pull request merged**
